M7R0
I&D_matX,%)anythingG6"F%[gl!"%!!!#_gt"S"S$""!F'$"cw:dg?y_6]]**zbFf0v#fmAKTJe$**
4(\@Tk7st]e0O[#\-(H74BYQ,NFdTwKMvQ])Qq5i%yCt!*ztzm<t![pPv=np&y!)p4Us)o,)[]4tBc8
UT"!$*>F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&$"cwv&GI5Rw0Dv***yP'z_P'HL6mq:z'*\&[21Ajgo`#z-=CY7&
[hX:J#p]njy?Q;nP>D%>N0J#RiO&**o)R$)eOSZ)oPf$[GR!\[5iV%3SCva'="y1rq!$+#F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&$"""F'F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F%,
I(eigVals7T^$F&F&F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2
F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F2F%,
I*K_eigVals7VX*-%(complexG6#%'sfloatGF%F%[gl"#%!!!""""F&F&X*F6F%F%[gl"#%!!!"#"#
F&F&F&F&X*F6F%F%[gl"#%!!!"$"$F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"%"%F&F&F&F&F&F&F&F&X
*F6F%F%[gl"#%!!!"&"&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"'"'F&F&F&F&F&F&F&F&F&
F&F&F&X*F6F%F%[gl"#%!!!"("(F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!")")F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"*"*F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&X*F6F%F%[gl"#%!!!"+"+F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl
"#%!!!",",F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"-"-F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!".".F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"/"/F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"0"0F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"1"1F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"2"2F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"3"3F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl
"#%!!!"4"4F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&X*F6F%F%[gl"#%!!!"5"5F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"6"6F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"7"7F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&X*F6F%F%[gl"#%!!!"8"8F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"9"9F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X
*F6F%F%[gl"#%!!!":":F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!";";F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&X*F6F%F%[gl"#%!!!"<"<F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"="=
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!">">F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"?"?F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F
%F%[gl"#%!!!"@"@F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"
A"AF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"B"BF&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"C"CF&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"D"DF&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"E"EF&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"F"FF&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"
#%!!!"G"GF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&X*F6F%F%[gl"#%!!!"H"HF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"I"IF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"J"JF&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F
%[gl"#%!!!"K"KF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"L"LF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"M"
MF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"N"NF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!
"O"OF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"P"PF&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&X*F6F%F%[gl"#%!!!"Q"QF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F6F%F%[gl"#%!!!"R"RF
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F1F1F1F%,
I.k_mod_eigVals7SF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F%,
I.K_mod_eigVals7SX*F$F%F%[gl!#%!!!""""F&X*F$F%F%[gl!#%!!!"#"#F&F&X*F$F%F%[gl!#%
!!!"$"$F&F&F&X*F$F%F%[gl!#%!!!"%"%F&F&F&F&X*F$F%F%[gl!#%!!!"&"&F&F&F&F&F&X*F$F%
F%[gl!#%!!!"'"'F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"("(F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!
")")F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"*"*F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"+"
+F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!",",F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!
!!"-"-F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!".".F&F&F&F&F&F&F&F&F&F&F&F&F&X*
F$F%F%[gl!#%!!!"/"/F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"0"0F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"1"1F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F
%[gl!#%!!!"2"2F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"3"3F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"4"4F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&X*F$F%F%[gl!#%!!!"5"5F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!
#%!!!"6"6F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"7"7F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"8"8F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"9"9F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!":":F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&X*F$F%F%[gl!#%!!!";";F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&X*F$F%F%[gl!#%!!!"<"<F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F
$F%F%[gl!#%!!!"="=F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F
%F%[gl!#%!!!">">F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F
%F%[gl!#%!!!"?"?F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F
$F%F%[gl!#%!!!"@"@F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&X*F$F%F%[gl!#%!!!"A"AF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&X*F$F%F%[gl!#%!!!"B"BF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"C"CF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"D"DF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"E"EF&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"F"FF&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!
#%!!!"G"GF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&X*F$F%F%[gl!#%!!!"H"HF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"I"IF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"J"JF&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F
%[gl!#%!!!"K"KF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"L"LF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"M"MF&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*
F$F%F%[gl!#%!!!"N"NF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"O"OF&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!
!!"P"PF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"Q"QF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"R"
RF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F%,
I/k_sec_singVals7SF&F&F+F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.F.$"#5!""F[sF[sF[sF[s
F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF%,
I+k_singVals7SF&F(F(F(F(F(F(F(F(F(F(F(F(F(F(F(F(F(F(F(F(F(F(F(F(F(F(F(F(F(F(F(F
(F(F(F(F(F(F(F(F(F(F(F(F(F(F(F(F(F%,
I+K_singVals7SX*F9F%F%[gl!#%!!!""""F&X*F9F%F%[gl!#%!!!"#"#F(F&X*F9F%F%[gl!#%!!!
"$"$F(F+F&X*F9F%F%[gl!#%!!!"%"%F(F.F+F&X*F9F%F%[gl!#%!!!"&"&F(F[sF.F+F&X*F9F%F%
[gl!#%!!!"'"'F(F[sF[sF.F+F&X*F9F%F%[gl!#%!!!"("(F(F[sF[sF[sF.F+F&X*F9F%F%[gl!#%
!!!")")F(F[sF[sF[sF[sF.F+F&X*F9F%F%[gl!#%!!!"*"*F(F[sF[sF[sF[sF[sF.F+F&X*F9F%F%
[gl!#%!!!"+"+F(F[sF[sF[sF[sF[sF[sF.F+F&X*F9F%F%[gl!#%!!!",",F(F[sF[sF[sF[sF[sF[
sF[sF.F+F&X*F9F%F%[gl!#%!!!"-"-F(F[sF[sF[sF[sF[sF[sF[sF[sF.F+F&X*F9F%F%[gl!#%!!
!".".F(F[sF[sF[sF[sF[sF[sF[sF[sF[sF.F+F&X*F9F%F%[gl!#%!!!"/"/F(F[sF[sF[sF[sF[sF
[sF[sF[sF[sF[sF.F+F&X*F9F%F%[gl!#%!!!"0"0F(F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF.F
+F&X*F9F%F%[gl!#%!!!"1"1F(F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF.F+F&X*F9F%F%[gl
!#%!!!"2"2F(F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF.F+F&X*F9F%F%[gl!#%!!!"3"3F
(F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF.F+F&X*F9F%F%[gl!#%!!!"4"4F(F[sF[sF
[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF.F+F&X*F9F%F%[gl!#%!!!"5"5F(F[sF[sF[sF[s
F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF.F+F&X*F9F%F%[gl!#%!!!"6"6F(F[sF[sF[sF[sF[
sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF.F+F&X*F9F%F%[gl!#%!!!"7"7F(F.F[sF[sF[sF[
sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF+F&X*F9F%F%[gl!#%!!!"8"8F(F.F[sF[sF
[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF+F&X*F9F%F%[gl!#%!!!"9"9F(F.
F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF+F&X*F9F%F%[gl!#%!
!!":":F(F.F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF+F&X*
F9F%F%[gl!#%!!!";";F(F.F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[
sF[sF[sF[sF+F&X*F9F%F%[gl!#%!!!"<"<F(F.F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF
[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF+F&X*F9F%F%[gl!#%!!!"="=F(F.F[sF[sF[sF[sF[sF[sF[s
F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF+F&X*F9F%F%[gl!#%!!!">">F(F
.F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF+F
&X*F9F%F%[gl!#%!!!"?"?F(F.F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[
sF[sF[sF[sF[sF[sF[sF[sF[sF+F&X*F9F%F%[gl!#%!!!"@"@F(F.F[sF[sF[sF[sF[sF[sF[sF[sF
[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF+F&X*F9F%F%[gl!#%!!!"A
"AF(F.F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF
[sF[sF[sF[sF+F&X*F9F%F%[gl!#%!!!"B"BF(F.F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[s
F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF+F&X*F9F%F%[gl!#%!!!"C"CF(F.F[
sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[s
F[sF[sF[sF+F&X*F9F%F%[gl!#%!!!"D"DF(F.F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[
sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF+F&X*F9F%F%[gl!#%!!!"E"EF(
F.F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[
sF[sF[sF[sF[sF[sF[sF+F&X*F9F%F%[gl!#%!!!"F"FF(F.F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF
[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF+F&X*F9F%F
%[gl!#%!!!"G"GF(F.F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF
[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF+F&X*F9F%F%[gl!#%!!!"H"HF(F.F[sF[sF[s
F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF
[sF[sF[sF[sF[sF[sF+F&X*F9F%F%[gl!#%!!!"I"IF(F.F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[s
F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF+F&
X*F9F%F%[gl!#%!!!"J"JF(F.F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[s
F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF+F&X*F9F%F%[gl!#%!!!"
K"KF(F.F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[s
F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF+F&X*F9F%F%[gl!#%!!!"L"LF(F[sF[sF[sF
[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF.F[sF[sF[sF[sF[sF[sF[sF[sF[s
F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF+F&X*F9F%F%[gl!#%!!!"M"MF(F[sF[sF[sF[sF[sF[sF[sF
[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF.F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[s
F[sF[sF[sF[sF[sF[sF[sF+F&X*F9F%F%[gl!#%!!!"N"NF(F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF
[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF.F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[s
F[sF[sF[sF[sF[sF+F&X*F9F%F%[gl!#%!!!"O"OF(F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF
[sF[sF[sF[sF[sF[sF[sF[sF[sF.F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[s
F[sF[sF[sF[sF+F&X*F9F%F%[gl!#%!!!"P"PF(F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF
[sF[sF[sF[sF[sF[sF[sF[sF[sF.F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[s
F[sF[sF[sF[sF+F&X*F9F%F%[gl!#%!!!"Q"QF(F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF
[sF[sF[sF[sF[sF[sF[sF[sF[sF.F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[s
F[sF[sF[sF[sF[sF+F&X*F9F%F%[gl!#%!!!"R"RF(F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF
[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF.F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[s
F[sF[sF[sF[sF[sF[sF[sF+F&F%,
I(matgramX,F$F%F%[gl!"%!!!#d]u"T"TF/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'""#F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'
F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'
F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'
F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'
F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/
F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'
F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'
F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'
F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'
F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'
F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'
F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'
F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'
F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'
F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'
F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'
F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'
F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F
/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'
F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'
F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'
F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'
F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'
F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'
F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'
F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'
F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'
F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'
F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'
F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'
F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'
F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'
F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F/F'
F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F'F
'F'F'F'F'F'F'F'F'F'F'F/F%,
I+max_eigValF2F%,
I,max_singValF(F%,
I,mod_eigVals7TF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F%,
I/mod_max_eigValF&F%,
I(normPol7UX*F$F%F%[gl!#%!!!"T"TF.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F
+F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!
!!"T"TF&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F.F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%
F%[gl!#%!!!"T"TF&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F.F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F
&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&
F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%
!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F&F.
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F
%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#
%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$
F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"T
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!
#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F
$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"
TF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&
F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl
!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&F&X*
F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F
&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F.F&F&F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&F&F&X*F$F%F%[gl!#%!!!"T
"TF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F.F&F&F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&F&X*F$F%F%[g
l!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&F&X*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&
F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F&X
*F$F%F%[gl!#%!!!"T"TF&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F
&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F&F.F%,
I)singVals7TF(F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[
sF[sF.F[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF[sF+F&
F%,
I,prev_eigValF&F%,
I+sup_eigValF2F%,
I&x_max$FevF'F%,
I&x_min$F]sF'F%,
I#r1F/F%,
I#r2F'F%,
I#c1F'F%,
I#c2F'F%,
I"n"#]F%,
I&a_valF'F%,
I&b_valF/F%,
I&c_valF]sF%,
I&d_valF/F%,
I#m1F'F%,
I#m2F'F%
